server:
  port: 8080

spring:
  application:
   name: 'stress-testing-lab'
  datasource:
    url: jdbc:postgresql://factory-db:5432/factory-service
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create

summary-scheduler:
  export-path: '/var/temp_dir/'
